"""initial_schema

Revision ID: 8fcda3245909
Revises: 
Create Date: 2026-05-29 23:40:07.623236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcda3245909'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('print_number', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('raw_api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_print_number'), 'bills', ['print_number'], unique=False)
    op.create_index(op.f('ix_bills_term'), 'bills', ['term'], unique=False)
    op.create_table('committees',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('parties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proceedings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.Integer(), nullable=False),
    sa.Column('proceeding_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proceedings_date'), 'proceedings', ['date'], unique=False)
    op.create_index(op.f('ix_proceedings_term'), 'proceedings', ['term'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('impact_category', sa.String(length=100), nullable=True),
    sa.Column('raw_analysis_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('party_id', sa.String(length=50), nullable=True),
    sa.Column('seat_number', sa.Integer(), nullable=True),
    sa.Column('district_num', sa.Integer(), nullable=True),
    sa.Column('district_name', sa.String(length=150), nullable=True),
    sa.Column('voivodeship', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['party_id'], ['parties.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceeding_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['proceeding_id'], ['proceedings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voting_days_date'), 'voting_days', ['date'], unique=False)
    op.create_table('votings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('voting_number', sa.Integer(), nullable=False),
    sa.Column('sitting', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('topic', sa.String(length=200), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('yes_count', sa.Integer(), nullable=False),
    sa.Column('no_count', sa.Integer(), nullable=False),
    sa.Column('abstain_count', sa.Integer(), nullable=False),
    sa.Column('not_voted', sa.Integer(), nullable=False),
    sa.Column('total_votes', sa.Integer(), nullable=False),
    sa.Column('attendance_percent', sa.Float(), nullable=False),
    sa.Column('quorum_required', sa.Integer(), nullable=False),
    sa.Column('raw_api_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['voting_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club_voting_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.String(length=50), nullable=False),
    sa.Column('decision', sa.Enum('YES', 'NO', 'ABSTAIN', 'MIXED', name='votingdecision'), nullable=False),
    sa.Column('yes_count', sa.Integer(), nullable=False),
    sa.Column('no_count', sa.Integer(), nullable=False),
    sa.Column('abstain_count', sa.Integer(), nullable=False),
    sa.Column('not_voted_count', sa.Integer(), nullable=False),
    sa.Column('party_members_total', sa.Integer(), nullable=False),
    sa.Column('participation_percent', sa.Float(), nullable=False),
    sa.Column('raw_members_votes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('votes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('voting_id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('vote', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['politician_id'], ['politicians.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voting_id'], ['votings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('voting_id', 'politician_id', name='uq_voting_politician')
    )
    op.create_index(op.f('ix_votes_politician_id'), 'votes', ['politician_id'], unique=False)
    op.create_index(op.f('ix_votes_voting_id'), 'votes', ['voting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_voting_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_politician_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_table('club_voting_results')
    op.drop_table('votings')
    op.drop_index(op.f('ix_voting_days_date'), table_name='voting_days')
    op.drop_table('voting_days')
    op.drop_table('politicians')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_proceedings_term'), table_name='proceedings')
    op.drop_index(op.f('ix_proceedings_date'), table_name='proceedings')
    op.drop_table('proceedings')
    op.drop_table('parties')
    op.drop_table('committees')
    op.drop_index(op.f('ix_bills_term'), table_name='bills')
    op.drop_index(op.f('ix_bills_print_number'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
